aug:
  image_aug: true
  masked_language_model: true
backbone: vgg19_bn
cnn:
  hidden: 256
  ks:
  - - 2
    - 2
  - - 2
    - 2
  - - 2
    - 1
  - - 2
    - 1
  - - 1
    - 1
  ss:
  - - 2
    - 2
  - - 2
    - 2
  - - 2
    - 1
  - - 2
    - 1
  - - 1
    - 1
dataloader:
  num_workers: 3
  pin_memory: true
dataset:
  data_root: data_line
  image_height: 128
  image_max_width: 1024
  image_min_width: 32
  name: hw
  train_annotation: train_list.txt
  valid_annotation: val_list.txt
device: cuda:0
optimizer:
  max_lr: 0.001
  pct_start: 0.1
predictor:
  beamsearch: false
pretrain: pretrain/vgg_seq2seq.pth
quiet: false
seq_modeling: seq2seq
trainer:
  batch_size: 32
  checkpoint: checkpoint/seq2seq_checkpoint_7k.pth
  export: weights/seq2seq_7k.pth
  iters: 2400
  log: ./train.log
  metrics: 1400
  print_every: 200
  valid_every: 600
transformer:
  decoder_embedded: 256
  decoder_hidden: 256
  dropout: 0.1
  encoder_hidden: 256
  img_channel: 256
vocab: 'aAàÀảẢãÃáÁạẠăĂằẰẳẲẵẴắẮặẶâÂầẦẩẨẫẪấẤậẬbBcCdDđĐeEèÈẻẺẽẼéÉẹẸêÊềỀểỂễỄếẾệỆfFgGhHiIìÌỉỈĩĨíÍịỊjJkKlLmMnNoOòÒỏỎõÕóÓọỌôÔồỒổỔỗỖốỐộỘơƠờỜởỞỡỠớỚợỢpPqQrRsStTuUùÙủỦũŨúÚụỤưƯừỪửỬữỮứỨựỰvVwWxXyYỳỲỷỶỹỸýÝỵỴzZ0123456789!"#$%&''()*+,-./:;<=>?@[\]^_`{|}~ '
weights: pretrain/vgg_seq2seq.pth
